### ISSUE TITLE
Have you test it on resnet50 or larger networks?

### ISSUE THREAD

**Issue by Jar7** [anguyen8/deepface-emd#1]
Hello, Thanks for the great works!
I read the paper! I am wondering whether you have tested in arcface with resnet50 or larger networks? Would it still outperform other model without rank2? Thank you!

**Comment by haithanhp** [comment]
Thanks for a great question. Yes. We ran the test for larger networks and it can outperform others. 

<img width="357" alt="Screen Shot 2022-08-11 at 11 45 04 PM" src="https://user-images.githubusercontent.com/25809722/184299411-181f566f-f500-48db-b022-02bd45143517.png">

**Comment by anguyen8** [comment]
@Jar7 The table above is Table S.6. in our [arXiv paper](https://arxiv.org/abs/2112.04016). 

Yes, we did this test and found re-ranking still improves baselines, but with a smaller improvement.
