### ISSUE TITLE
alignment for 128x128?

### ISSUE THREAD

**Issue by dourcer** [anguyen8/deepface-emd#3]
Meaningful work, when I want to use 128 * 128 to align people's faces, but I don't find ref_pts For 128x128? I haven't found the converted code, can you provide it?
thanks!

**Comment by haithanhp** [comment]
Hi @dourcer,

Thanks for your interest in our work. You can use this commented [code](https://github.com/anguyen8/deepface-emd/blob/main/alignment/align_face.py#L27) in the alignment folder to crop images to 160x160 first and resize it to 128x128.
