### ISSUE TITLE
Convert pytorch model to onnx model?

### ISSUE THREAD

**Issue by vtn98** [anguyen8/deepface-emd#4]
Hi @anguyen8,
Thank your project.
I tried to convert resnet18_110.pth to onnx model, but the error:
"Unsupported: ONNX export of operator adaptive_avg_pool2d, output size that are not factor of input size. Please feel free to request support or submit a pull request on PyTorch GitHub."
Can you help me to solve this problem? Thank you.

**Comment by anguyen8** [comment]
Hi @vtn98 ,

Thank you for your interest! 

However, since we use the pre-trained model from [here](https://github.com/vtn98/arcface-pytorch) and you want to convert it into ONNX, I think you'd be better off asking on https://github.com/onnx/onnx .
