### ISSUE TITLE
Code of LMK

### ISSUE THREAD

**Issue by WisonZ** [anguyen8/deepface-emd#6]
I appreciate your insightful work, could you please release the code of LMK method?

**Comment by anguyen8** [comment]
@WisonZ Thanks for your question!

For LMK, we only use the [dlib](https://pyimagesearch.com/2017/04/03/facial-landmarks-dlib-opencv-python/) to get the landmarks for each face and then we create a heatmap by assigning each patch an importance score, which is equal to the normalized density of the numbers of landmarks per patch.

This method is a pretty naive landmark-based baseline and performs worse than APC.

We will try to upload the code for your reference!

**Comment by haithanhp** [comment]
Hi @WisonZ ,

We uploaded visualization code for lmks in [visualize_faces_lmk.py](https://github.com/anguyen8/deepface-emd/blob/main/visualize_faces_lmk.py). We have test inputs of images and JSON file of landmarks (obtained from dlib).  You can see the sample results here: [heatmap_face_lmk.jpg](https://github.com/anguyen8/deepface-emd/blob/main/results/heatmap/heatmap_face_lmk.jpg).
